### PR TITLE
Fix authentication issue

### PR DESCRIPTION
**Pull request by amirsanni**

### CODE REVIEW

**Comment by sylnit** [comment]
I've tested it. It didn't fix it. Still returned the 401 error.

**Comment by amirsanni** [comment]
Sorry, how did you do the test? Did you download the repo and create a test file?

**Comment by amirsanni** [comment]
It didn't fix it.

**Comment by sylnit** [comment]
For a quick test, I got into the vendors folder and made the addition directly to the PhpEwsWrapper class and tested. And it didn't work.

**Comment by amirsanni** [comment]
The fix is not just in the phpewswrapper class. The dependency was changed as well. You can  install the v1.2 version via composer and test with that.

**Comment by sylnit** [comment]
I have installed the dependencies and it gives me the error:

Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method jamesiarmes\PhpEws\Client::authWithUserAndPass()

Is there anything extra I need to do?

**Pull request merged**
